version: "3"

tasks:
  test-aur-pkg:
    desc: "Test building the AUR package"
    cmds:
      - >-
        docker run -it --rm
        -v "$PWD":/pkg
        archlinux:latest
        bash -lc "pacman -Sy --noconfirm base-devel git &&
        useradd -m builder &&
        chown -R builder:builder /pkg &&
        su builder -c 'cd /pkg && makepkg -s --noconfirm'"
